version: "3.7"

services:
  fastapi:
    build: fastAPI
    image: 108478/fastapi:latest
    networks: 
      - api-net
    ports: 
      - 80:80
  
  client:
    build: client
    image: 108478/client:latest
    networks:
      - api-net
    depends_on: 
      - fastapi
    stdin_open: true
    tty: true

networks:
  api-net:
    driver: bridge