FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
#Offical FastAPI Docker Image
#https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/python3.7.dockerfile
#https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/blob/master/docker-images/python3.7.dockerfile

COPY ./app /app
